namespace: enfence
name: powerha_aix
version: 1.2.1
readme: README.md

authors:
  - Andrey Klyachkin <info@power-devops.com>


description: IBM PowerHA SystemMirror 7.2.X cluster management

license:
  - GPL-3.0-only

tags: [power, aix, ibmpower, ibmaix, powerha, cluster, infrastructure, application, tools]

dependencies: {}

repository: http://github.com/power-devops/powerha_aix
documentation: https://power-devops.github.io/powerha_aix/
homepage: http://www.enfence.com
issues: http://github.com/power-devops/powerha_aix/issues

build_ignore: []
