---
- name: Mount NFS share
  ibm.power_aix.mount:
    state: mount
    node: "{{ cluster_update_nfs_server }}"
    mount_dir: "{{ cluster_update_nfs_share }}"
    mount_over_dir: "{{ cluster_update_local_dir }}"
    options: "{{ cluster_update_nfs_options }}"

- name: Install PowerHA updates
  ibm.power_aix.install_all_updates:
    device: "{{ cluster_update_local_dir }}"
    agree_licenses: true
    extend_fs: true

- name: Unmount NFS share
  ansible.posix.mount:
    state: unmounted
    path: "{{ cluster_update_local_dir }}"
    fstab: /dev/null
