# powerha_source: (path) directory where PowerHA filesets can be found
powerha_source: /phainst/installp/ppc

# powerha_filesets: (str) PowerHA filesets to install
powerha_filesets: "cluster.es.server cluster.es.client"

# aix_source: (path) directory with AIX filesets
aix_source: /usr/sys/inst.images

# aix_filesets: (str) AIX base filesets to install prior PowerHA installation
aix_filesets: "bos.ahafs bos.cluster.rte bos.clvm rsct.basic.rte"

# nodes: (array of dict) nodes of the cluster
# each item has two fields:
# - name: name of the node
# - ip: IP address of the node
nodes: []

# service: (array of dict) service ip labels
# each item has two fields:
# - name: name of the node
# - ip: IP address of the node
service: []

# app: (dict) application controller resource
# Fields:
# - name: (str) name of the application controller. not used in this role
# - start: (str) path to the script to start the application
# - stop: (str) path to the script to stop the application
app:
  name: "ac_ora"
  start: "start_app.sh"
  stop: "stop_app.sh"
