---
- name: Delete cluster
  hosts: all
  tasks:
    - name: Stop cluster
      enfence.powerha_aix.cluster:
        name: cluster1
        state: stopped
    - name: Delete cluster
      enfence.powerha_aix.cluster:
        name: cluster1
        state: absent
