---
- name: Create cluster
  hosts: all
  tasks:
    - name: Create /etc/cluster/rhosts
      ansible.builtin.copy:
        content: "10.11.12.21\n10.11.12.22\n"
        dest: /etc/cluster/rhosts
        owner: root
        group: system
        mode: "0600"
      notify:
        - Restart clcomd
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create a cluster
      enfence.powerha_aix.cluster:
        name: cluster1
        state: present
        repos:
          - hdisk1
        nodes:
          - node1
          - node2
    - name: Start cluster
      enfence.powerha_aix.cluster:
        name: cluster1
        state: started
    - name: Add service label
      enfence.powerha_aix.service_ip:
        name: oracle
      notify: "Synchronize cluster"
    - name: Add application controller
      enfence.powerha_aix.appcontroller:
        name: ac_oracle
        start: /usr/local/bin/start_ora
        stop: /usr/local/bin/stop_ora
        mode: foreground
      notify: "Synchronize cluster"
    - name: Add resource group
      enfence.powerha_aix.rg:
        name: rg_oracle
        nodes:
          - node1
          - node2
        startup: OHN
        fallover: FNPN
        fallback: NFB
        service: ['oracle']
        application: ['ac_oracle']
        volgrp:
          - vg01
          - vg02
          - vg03
      notify: "Synchronize cluster"
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Bring rg_oracle online
      enfence.powerha_aix.rg:
        name: rg_oracle
        state: started

  handlers:
    - name: Stop clcomd # noqa: no-changed-when
      ansible.builtin.command:
        cmd: stopsrc -s clcomd
      ignore_errors: true # noqa: ignore-errors
      listen: "Restart clcomd"

    - name: Wait 5 seconds...
      ansible.builtin.pause:
        seconds: 5
      listen: "Restart clcomd"

    - name: Start clcomd # noqa: no-changed-when
      ansible.builtin.command:
        cmd: startsrc -s clcomd
      listen: "Restart clcomd"

    - name: Synchronize cluster
      enfence.powerha_aix.cluster:
        name: cluster1
        fix: true
        state: synced
